// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpicyRazorTemp.Data;

#nullable disable

namespace SpicyRazorTemp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SpicyRazorTemp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categoiries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A gentle touch of spice for those who prefer a subtle flavor.",
                            DisplayOrder = 1,
                            Name = "Mild"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A balanced level of spice that adds a bit of heat without overwhelming.",
                            DisplayOrder = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Description = "For those who enjoy a strong kick of spice that packs a punch.",
                            DisplayOrder = 3,
                            Name = "Hot"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Intense heat for spice lovers who crave a fiery experience.",
                            DisplayOrder = 4,
                            Name = "Extra Hot"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A blazing level of spice that challenges even the bravest.",
                            DisplayOrder = 5,
                            Name = "Super Spicy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
