// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpicyWorld.Data;

#nullable disable

namespace SpicyWorld.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240818060934_seedCategories")]
    partial class seedCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpicyWorld.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categoiries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            DisplayOrder = 1,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            DisplayOrder = 2,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            DisplayOrder = 3,
                            Name = "Grey"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
